name = "resume-api"
main = "src/index.ts"
compatibility_date = "2025-01-12"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
ALLOWED_ORIGINS="https://anelfdz.com,https://www.anelfdz.com"

[[kv_namespaces]]
binding = "RESUME_KV"
id = "e4178d3bd77847b69aa7530fef54912e"

[observability.logs]
enabled = true

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1